Document: libfusekit
Title: Debian libfusekit Manual
Author: <insert document author here>
Abstract: This manual describes what libfusekit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfusekit/libfusekit.sgml.gz

Format: postscript
Files: /usr/share/doc/libfusekit/libfusekit.ps.gz

Format: text
Files: /usr/share/doc/libfusekit/libfusekit.text.gz

Format: HTML
Index: /usr/share/doc/libfusekit/html/index.html
Files: /usr/share/doc/libfusekit/html/*.html
